/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : cURL
 #	author : miyako
 #	2015/01/23
 #
 # --------------------------------------------------------------------------------*/



// --- cURL
void _cURL(sLONG_PTR *pResult, PackagePtr pParams);
void cURL_Escape_url(sLONG_PTR *pResult, PackagePtr pParams);
void cURL_Unescape_url(sLONG_PTR *pResult, PackagePtr pParams);
void cURL_Get_version(sLONG_PTR *pResult, PackagePtr pParams);
void cURL_Get_date(sLONG_PTR *pResult, PackagePtr pParams);
void cURL_Get_executable(sLONG_PTR *pResult, PackagePtr pParams);

